const HttpsProxyAgent = require('https-proxy-agent');
const google = require('googleapis');
const _ = require('lodash');
const ga = require('../config/nodeAnalytics-b11967f9e384.json');
const programs = require('../config/program_mapping.json');
const loc = require('../config/locations.json');
const moment = require('moment');
const when = require('when');

const { proxy, view_id } = loc;
const agent = new HttpsProxyAgent(proxy);

// Configure the parameters neccessary for the queries
const config = {
  pageData: {
    metrics: 'ga:pageviews, ga:avgTimeOnPage',
    dimensions: 'ga:pageTitle',
    skey: '-ga:pageviews',
    ikey: 'pagetitles',
  },
  adWordData: {
    metrics: 'ga:impressions, ga:adClicks',
    dimensions: 'ga:adDestinationUrl',
    skey: '-ga:adClicks',
    ikey: 'urls',
  },
};

// Define Google Client with JSON Auth File generated by Google Developer Console
const jwtClient = new google.auth.JWT(
  ga.client_email,
  null,
  ga.private_key,
  ['https://www.googleapis.com/auth/analytics.readonly'],
);

// Return the id paramter from program mapping object
const matchProgram = (program, ikey) => {
  const id = {};
  for (let x = 0; x < programs.length; x += 1) {
    if (programs[x].id === program) {
      id[ikey] = programs[x][ikey];
    }
  }
  return id[ikey];
};

// Extract relevant data from query results
const extractProgramData = (data, program, ikey, cb) => {
  const match = matchProgram(program, ikey);
  const result = {};
  for (let x = 0; x < data.rows.length; x += 1) {
    for (let y = 0; y < match.length; y += 1) {
      if (data.rows[x][0] === match[y]) {
        for (let k = 1; k < data.rows[x].length; k += 1) {
          result[`metric${k}`] = Number(data.rows[x][k]);
        }
      }
    }
  }
  cb(result);
};

// Define Query to Analytics
const queryData = (analytics, program, dates, conf, cb) => {
  analytics.data.ga.get({
    auth: jwtClient,
    ids: view_id,
    metrics: conf.metrics,
    dimensions: conf.dimensions,
    'start-date': moment(dates.startdate, 'YYYY-MM-DD').format('YYYY-MM-DD'),
    'end-date': moment(dates.enddate, 'YYYY-MM-DD').format('YYYY-MM-DD'),
    sort: conf.skey,
    maxresults: 100,
  }, (err, response) => {
    if (err) {
      return err;
    }
    return extractProgramData(response, program, conf.ikey, cb);
  });
};

// Export function that invoces authorization and performs the query
exports.getData = (program, startdate, enddate, cb) => {
  const queries = [];
  const response = {};
  google.options({ proxy, agent });
  const dates = {
    startdate,
    enddate,
  };
  jwtClient.authorize((err) => {
    if (err) {
      return err;
    }
    const analytics = google.analytics('v3');
    // Map over config object and create new query for every key
    _.forOwn(config, (value, key) => {
      queries.push(when.promise((resolve) => {
        queryData(analytics, program, dates, config[key], (result) => {
          resolve(result);
        });
      })
        .then((val) => {
          response[key] = val;
        }));
    });
    return when.all(queries)
      .then(() => { cb(response); });
  });
};
